### ISSUE TITLE
Notebook not auto-starting when opening .ju.py file (Windows)

### ISSUE THREAD

**Issue by sho-87** [kiyoon/jupynium.nvim#42]
I have my config setup to auto start and attach a server:
```
		auto_start_server = {
			enable = true,
			file_pattern = { "*.ju.*" },
		},
		auto_attach_to_server = {
			enable = true,
			file_pattern = { "*.ju.*" },
		},
```
However, when I open a `*.ju.py` file the server doesn't start automatically.

I have confirmed that manually starting/attaching with `:JupyniumStartAndAttachToServer` works OK

My config: https://github.com/sho-87/dotfiles/blob/master/nvim/lua/plugins/modules/jupynium.lua

**Comment by kiyoon** [comment]
I don't know if #41 and this is related. But I think for this one it may be because of your lazy loading strategy.
First of all I think `ft = "ju.*"` is wrong. Unfortunately there's no filetype for jupynium so you can just say `ft = "python"`.

**Comment by sho-87** [comment]
ah yes both this and #41 were due to lazy loading

minor request: is it possible at some point to refactor the Jupynium commands so that they can receive args ( e.g. `Jupynium StartSync` and `Jupynium AttachToServer`) rather than each one being a differently named command? That way the plugin can be lazy loaded using a single `Jupynium` command rather than on a generic python filetype or on a long list of different commands?

**Comment by kiyoon** [comment]
Yes, by the time I was writing this I didn't think about that, and that's a fair point at some point I'll need to refactor

**Comment by kiyoon** [comment]
But if you want auto start, you don't want it to lazy load because it needs to be loaded before the file. I need to think how to improve this

**Comment by kiyoon** [comment]
How about this?

```lua
    cond = function()
      return vim.fn.expand("%:n"):match [[.*%.ju%..*]] ~= nil
    end,
```

Then only `*.ju.*` file will load Jupynium.

**Comment by sho-87** [comment]
Ive turned off autostart for now as I find the plugin more useful without it, but ill wait for an eventual refactor as those methods have restrictions dont fit well with my workflow

**Comment by kiyoon** [comment]
What I can maybe do is to make cmds in two forms for now, deprecating the others over time.

I wonder if I should group the commands as well.

`Jupynium kernel_restart`  
or  
`Jupynium kernel restart`

The second way may be more organised, but I guess we don't have too many commands available anyway and it may make it harder to type and find the commands.

What do you think?

**Comment by sho-87** [comment]
I think `Jupynium kernel_restart` would be ok. there aren't too many kernel commands, and going to 2 level commands might just make things harder to autocomplete

**Comment by kiyoon** [comment]
On a second thought, you probably don't need or want to lazy load Jupynium. It's very minimal and it takes like 1ms to start up. The core part is implemented in Python so before the jupynium server starts there's nothing that'll take time to load.

All it does is just creating vim commands and autocmds. By lazy loading it will cause problems like you had, because the autocmds won't be called.

I think specifying `ft` is enough.

**Comment by kiyoon** [comment]
Let me know if it takes long time to load. It could be a Windows specific bug

**Comment by kiyoon** [comment]
You can try `cmd = { "JupyniumStartAndAttachToServer", "JupyniumAttachToServer" }`because these cmds need to be called before using anything else anyways. Again you may have some problem by doing this.

I found that it is difficult to group the commands, because there are two parts where the cmds are initialised. The plugin initialises basic commands to launch Jupynium. The core initialises additional commands once you attach Jupynium. It's not trivial to group those into one.

The reason I did this approach is that 1. some people want to use Jupynium on a remote server. Then we need to ensure that the python core and the plugin version is the same. This can go wring and cause issues.
2. It's more intuitive to show commands that are available first

**Comment by sho-87** [comment]
that makes sense. I will try loading on those 2 commands and see if it works.
